orbit.client.url-base: http://localhost:8000
orbit.client.url-positions: ${orbit.client.url-base}/api/v1/orbits/positions
orbit.client.url-distances: ${orbit.client.url-base}/api/v1/conjunctions/distances
orbit.client.url-health: ${orbit.client.url-base}/health

weather.client.url-base: http://localhost:8001
weather.client.url-space-weather: ${weather.client.url-base}/space-weather
