weather.client.url-base: http://localhost:8000
weather.client.url-positions: ${weather.client.url-base}/api/v1/orbits/positions
weather.client.url-distances: ${weather.client.url-base}/api/v1/conjunctions/distances
weather.client.url-health: ${weather.client.url-base}/health
