orbit.client.url-base: http://92.255.110.133:8000
orbit.client.url-positions: ${orbit.client.url-base}/api/v1/orbits/positions
orbit.client.url-distances: ${orbit.client.url-base}/api/v1/conjunctions/distances
orbit.client.url-health: ${orbit.client.url-base}/health

weather.client.url-base: http://localhost:8001
weather.client.url-space-weather: ${weather.client.url-base}/space-weather

eva.client.url-base: http://92.255.110.133:8001
eva.client.url-windows: ${eva.client.url-base}/api/v1/eva/windows
eva.client.url-health: ${eva.client.url-base}/health
